# Generated by Django 5.2.1 on 2025-05-29 22:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='VWOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vwo_account_id', models.IntegerField(default=1, help_text='You can find this in your VWO dashboard under Account Settings', validators=[django.core.validators.MinValueValidator(1)], verbose_name='VWO Account ID')),
                ('async_load', models.CharField(choices=[('async', 'Asynchronous'), ('sync', 'Synchronous')], default='async', help_text='Choose how the VWO tracking script loads on your site. Asynchronous is recommended for faster page loads.', max_length=5, verbose_name='SmartCode Loading Type')),
                ('settings_tolerance', models.IntegerField(default=2500, help_text='Maximum wait time for VWO settings to be applied. Must be 2500ms or higher.', validators=[django.core.validators.MinValueValidator(2500)], verbose_name='Settings Tolerance (ms)')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'VWO Settings',
            },
        ),
    ]
